CREATE DATABASE IF NOT EXISTS delivery_worker DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE delivery_worker;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL,
  phone VARCHAR(20) NOT NULL UNIQUE,
  employee_id VARCHAR(32) NULL UNIQUE,
  password_hash VARCHAR(128) NULL,
  avatar VARCHAR(255) NULL,
  user_type VARCHAR(16) NOT NULL DEFAULT 'temp',
  role VARCHAR(32) NOT NULL DEFAULT 'temp',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sms_codes (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  phone VARCHAR(20) NOT NULL UNIQUE,
  code VARCHAR(12) NOT NULL,
  expire_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  assignee_user_id BIGINT NOT NULL,
  order_no VARCHAR(64) NOT NULL,
  customer_name VARCHAR(128) NOT NULL,
  address VARCHAR(255) NOT NULL,
  scheduled_time VARCHAR(32) NOT NULL,
  goods_count INT NOT NULL DEFAULT 0,
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  status_text VARCHAR(32) NOT NULL DEFAULT '待开始',
  has_arrive TINYINT(1) NOT NULL DEFAULT 0,
  has_complete TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_tasks_assignee (assignee_user_id)
);

CREATE TABLE IF NOT EXISTS checkins (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  biz_id VARCHAR(64) NOT NULL UNIQUE,
  user_id BIGINT NOT NULL,
  checkin_type VARCHAR(16) NOT NULL,
  checkin_date DATE NOT NULL,
  checkin_time VARCHAR(16) NOT NULL,
  task_id BIGINT NULL,
  order_no VARCHAR(64) NULL,
  latitude DECIMAL(10,6) NULL,
  longitude DECIMAL(10,6) NULL,
  address VARCHAR(255) NULL,
  photos_json LONGTEXT NULL,
  remark VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_checkins_user_date (user_id, checkin_date)
);

CREATE TABLE IF NOT EXISTS uploaded_files (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  biz_type VARCHAR(32) NOT NULL DEFAULT 'common',
  file_name VARCHAR(255) NOT NULL,
  file_url VARCHAR(500) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_uploaded_user (user_id)
);

CREATE TABLE IF NOT EXISTS reimbursement_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  biz_id VARCHAR(64) NOT NULL UNIQUE,
  user_id BIGINT NOT NULL,
  order_id BIGINT NULL,
  order_no VARCHAR(64) NULL,
  type VARCHAR(32) NOT NULL,
  type_name VARCHAR(64) NOT NULL,
  type_icon VARCHAR(16) NULL,
  amount DECIMAL(10,2) NOT NULL,
  expense_date DATE NOT NULL,
  description VARCHAR(255) NULL,
  invoices_json LONGTEXT NULL,
  bill_images_json LONGTEXT NULL,
  other_images_json LONGTEXT NULL,
  require_invoice TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  status_text VARCHAR(32) NOT NULL DEFAULT '审核中',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_reimbursement_user (user_id)
);

CREATE TABLE IF NOT EXISTS problem_reports (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  biz_id VARCHAR(64) NOT NULL UNIQUE,
  user_id BIGINT NOT NULL,
  order_id BIGINT NULL,
  order_no VARCHAR(64) NULL,
  type VARCHAR(32) NOT NULL,
  type_name VARCHAR(64) NOT NULL,
  type_icon VARCHAR(16) NULL,
  detail_json LONGTEXT NULL,
  photos_json LONGTEXT NULL,
  remark VARCHAR(255) NULL,
  expectation VARCHAR(16) NULL,
  summary VARCHAR(255) NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  status_text VARCHAR(32) NOT NULL DEFAULT '待处理',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_problem_user (user_id)
);
